### ISSUE TITLE
[1.8.0] Adjustable backpack spams log every tick

### ISSUE THREAD

**Issue by Syndaryl** [Aroma1997/BetterChests#88]
When the adjustable backpack is in my inventory, my log gets spammed with a massive number of some kind of debug number:

[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:11] [Server thread/INFO]: 1475224461 1
[08:24:12] [Server thread/INFO]: 1475224461 1
[08:24:12] [Server thread/INFO]: 1475224461 1
[08:24:12] [Server thread/INFO]: 1475224461 1
[08:24:12] [Server thread/INFO]: 1475224461 1
[08:24:12] [Server thread/INFO]: 1475224461 1
[08:24:12] [Server thread/INFO]: 1475224461 1
[08:24:12] [Server thread/INFO]: 1475224461 1

etc etc. If I take it out of my inventory, it stops. If I put it back in, it starts again and I get different numbers.

**Comment by Aroma1997** [comment]
Fixed in the last dev build.

**Comment by Syndaryl** [comment]
Where do I pick up the last dev build? Your thread is still showing 1.2.0.0

**Comment by Aroma1997** [comment]
You can get it from here ( http://ci.aroma1997.org/job/BetterChests/ ). Keep in mind that some builds are for MC 1.8
